### PR TITLE
Building with Bootstrap! Newsweek clone

### PR DESCRIPTION
**Pull request by lmaldonadoch**
On this project, I learned what the Bootstrap framework is and how to use it. I applied all the previously acquired knowledge on responsive design, positioning elements and media queries along with the Bootstrap classes to create a fully responsive website. 

## Project milestones
- Build a complete website from scratch using the Bootstrap Framework.
- Make a website fully responsive.
- Practice our previously acquired knowledge on HTML and CSS including Grid, Flexbox, Float, Background Images, and media queries.

The requirements we were able to meet for this project were:

## General requirements:
- [x] Add a descriptive README file to your repositories as described here.
- [x] Use meaningful names for your Pull Requests and add a short summary of its content as described here.
- [x] Use descriptive commit messages as described here.
- [x] Do not commit files that are not related to the project. Instead, add them to .gitignore file.
- [x] Do not commit inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history.

## Section:
- [x] Keep your code clean.
- [x] Remember to use semantic HTML.
- [x] Validate your HTML markup with validator (as described here).
- [x] Make sure you DON’T make common mistakes in your CSS styles.

## Project-specific
- [x] Remember to use Bootstrap CSS classes wherever it is possible - this is the main point of this project.
- [x] As you can use a ready set of CSS classes, be more precise and make sure that your page looks exactly the same as the source page.
- [x] Remember to double-check that your page layout does not break on smaller screens.

### CODE REVIEW

**Comment by Dandush03** [comment]
# :red_circle: Status Require: changes :muscle: 
### Hey :wave: 
## Good attempts on this one :muscle: :+1: 

### This page is a clone page from the [newsweek](https://www.newsweek.com/), therefore there are a few changes you have to fix in order to achieve it

### Check all requirements marked below :point_down: 

### [__NOTICE__]: I would not repeat previews mistake. Make sure you fix them in all views.

---

---

# Phone Resolution (Default Width)


---

---

## Please make sure that you have place the correct order of your elements in this view

### Correct Order:
    - Nav
    - Top Story
    - Featured Stories
    - Opinion
    - The Debate
    - More Story
    - Heroes of the Pandemic
    - Culture & Travel
    - Latest News
    - SingUp (add)
    - In the Magazine
    - Editor's Pick
    - Subscribe
    - Newsletter
    - Footer

---

### In this resolution beside ordering your project looks great!

---

---

# Pad Resolution (min-Width: 768px)

---

---

## Please make sure that you have place the correct order of your elements in this view

### Correct Order:
    - Nav
    - Featured Stories || Top Story
    - Featured Stories || Heroes of the Pandemic
    - Featured Stories || Culture & Travel
    - Featured Stories || More Stories
    - Opinion
    - The Debate
    - Latest News
    - In the Magazine
    - Editor's Pick
    - Subscribe
    - Newsletter
    - Footer

---

### This section isn't actually responsive as the original, check that all your section behave the same way as in the phone view instead of adopting a different layouts

##### Required:
Screenshot from 2020-04-14 20-44-29
##### Yours: 
Screenshot from 2020-04-14 20-44-46

---

---

# Desktop Resolution Resolution (min-Width: 1025px)

---

---

### Correct Order:
    - Nav
    - Featured Stories || Top Story
    - Featured Stories || Heroes of the Pandemic
    - Featured Stories || Culture & Travel
    - Featured Stories || More Stories
    - Opinion
    - The Debate
    - Latest News
    - In the Magazine
    - Editor's Pick
    - Subscribe
    - Newsletter
    - Footer

---

## Header
- [x] Element doesn't have proper alignment.
- [x] Subscribe button missing padding
##### Required:
Screenshot from 2020-04-14 20-38-30
##### Yours: 
Screenshot from 2020-04-14 20-38-14
---

## Nav-Bar
- [x] Missing Separator line (border-bottom maybe?)
##### Required:
Screenshot from 2020-04-14 20-38-52
##### Yours: 
Screenshot from 2020-04-14 20-38-41

---

## Basic Structure
- [x] Your page is missing a max-width to center all your container, it brakes on large screens
##### Required:
Screenshot from 2020-04-14 20-39-19
##### Yours: 
Screenshot from 2020-04-14 20-39-02

---

## More Stories
- [x] This section shouldn't have a scroll bar.
##### Required:
Screenshot from 2020-04-14 20-39-41
##### Yours: 
Screenshot from 2020-04-14 20-39-50


---

## The Magazine
- [x] First Picture should cover the same size as the others images+title
- [x] Pictures too wide (Probably due to the missing max width)
##### Required:
Screenshot from 2020-04-14 20-40-17
##### Yours: 
Screenshot from 2020-04-14 20-40-03

---

## Footer
- [x] Wrong items alignment
##### Required:
Screenshot from 2020-04-14 20-40-52
##### Yours: 
Screenshot from 2020-04-14 20-40-43

---

## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by lmaldonadoch** [comment]
Hi!!! Thank you for the comments! Here are the observations resolved:

- [x] Ordered the elements in the correct way. 
> Done! All were correct except for mobile, I forgot to hide some elements for this resolution.

- [x] This section isn't actually responsive as the original, check that all your section behave the same way as in the phone view instead of adopting a different layouts
> Done! Kindly make sure you are using the same zoom for both websites since the responsiveness is based on width. By looking at the screenshots, it seems like the zoom you are using on my website is more than the one you are using on the original hence the responsiveness has not kicked in yet.

- [x] Element doesn't have proper alignment.
> Done! I used defined with to the extreme elements so that the center can get centered using justify-content-center. 

- [x] Subscribe button missing padding.
> Done! Thank you for pointing it out!

- [x] Missing Separator line (border-bottom maybe?)
> It was there! Maybe because of the zoom it was not clear but it has a lower margin, I just increased it by 1px to make it stand out more. Here is the screenshot:
image

- [x] Your page is missing a max-width to center all your container, it brakes on large screens
> Done! I noticed it right after I submitted the review request but I guess you beat me at it haha. Thanks for pointing it out!

- [x] This section shouldn't have a scroll bar.
> Hmmm this is a tricky one since I don't know how to make it exactly like the website. I guess we need some Javascript or jQuery? If I am mistaken, kindly help me with some resources to read through since I couldn't find any without messing with those tools. Because of that, I decided to make it scrollable since I thought that would be the closest approach to the actual website but I had removed it and then I faced 2 options, either I let the website look ugly because of the large section or I cut it with an "overflow: hidden" rule. I decided on the second one.

- [x] First Picture should cover the same size as the others images+title
> Done! Thank you for pointing out, I just applied some hight

- [x] Pictures too wide (Probably due to the missing max-width)
> Done! Once the hight was correct, they looked much better, thank you for pointing it out!

- [x] Wrong items alignment
> Done! Once I applied the max-width to the body it corrected itself. Thank you for pointing it out! 

Thanks for the observations!

Happy coding!

**Comment by uryelah** [comment]
Hello **Luis Maldonado Chávez**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, your project is looking very impressive. You really have an eye for detail!🌟**

Not only is your communication skills are off charts but your project responsiveness is also great! There's only one issue you missed from the last review that you need to work through to get this project accepted. I'm sure it will be a piece of cake for someone of your skill level though! 💪

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] The red text for the 'Featured stories' and 'Top story' should be above the article's image with a transparent white background under it. Not under it like in your version.
Compare your article and the original one below:
Screenshot_2020-04-15 Document
--
Screenshot_2020-04-15 Newsweek

- [ ]  [OPTIONAL] Change the `title` tag in your HTML head so it's 'Newsweek' or similar. It's easier to identify the tab that way, and you can even add an icon to it if you are feeling ambitious.

------

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by lmaldonadoch** [comment]
@uryelah thank you so much for your kind words! I feel truly flattered. 

Here are the comments on the request:

- [x]  [OPTIONAL] Change the title tag in your HTML head so it's 'Newsweek' or similar. It's easier to identify the tab that way, and you can even add an icon to it if you are feeling ambitious.
> Done! Thank you, I didn't really know what the title was for, now I see it :)

- [x] The red text for the 'Featured stories' and 'Top story' should be above the article's image with a transparent white background under it. Not under it like in your version.
Compare your article and the original one below:
> Kindly share with me the resolution/scenario on when the error happened, since I looked through all xs/sm/md/lg/xl and I could not replicate that same error you mentioned. These are the screenshots of what I am seeing from the [Live Version](https://rawcdn.githack.com/lmaldonadoch/newsweek-clone/4e85f556ba2db214cec62c5506e1583c009cd477/index.html) of the website:
image

image

image

Thank you so much! Happy coding

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED**  :1st_place_medal: :100: :fireworks: 

Hi @lmaldonadoch :smile: 

Congrats on the hard work, your project looks beautiful and professional and it is approved :fireworks: :fireworks: :fireworks:

The :bug: (bug) Sarah mentioned is on the Mozilla browser, when I checked on the chrome it looks as your prints.


If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)

### **Happy coding and good luck on the next project**  :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Pull request merged**
